module.exports = [
  {
    title: 'Introductory Blog Post',
    slug: 'introductory-blog-post',
    body: `Here's the first post on the site! It's well-written, informative, and entirely composed of typesetter's placeholder text. Amazing!\n\nAute dolore mollit minim ipsum ea. Sunt dolor tempor nulla do amet aliquip amet in. Ad do laboris cupidatat qui consequat fugiat cupidatat quis enim ex consectetur reprehenderit ullamco eu. Id minim ea veniam culpa deserunt nostrud minim pariatur adipisicing elit do aliquip ipsum. Nisi cupidatat sint labore dolor dolore nisi tempor voluptate veniam laboris.\n\nSunt officia ipsum pariatur nostrud ex aute qui exercitation cupidatat minim incididunt. Ut voluptate ullamco occaecat qui incididunt commodo commodo cupidatat id labore. Nisi ex sint ipsum sint nulla. Cupidatat anim amet laborum eiusmod aliqua veniam sit aute tempor sunt incididunt dolor id exercitation. Officia dolor laboris commodo labore sint quis consectetur mollit amet do aute enim sint nisi. Elit ad nulla tempor ipsum ullamco qui fugiat veniam nisi enim ut. Incididunt culpa anim amet proident.\n\nEst exercitation ut et exercitation nostrud elit nisi eu. Proident laborum magna voluptate magna exercitation sunt officia non sit. Officia ea sit exercitation incididunt duis consectetur occaecat qui dolor id duis consequat exercitation aliquip. Aliqua anim est esse ad do mollit anim eu enim officia.\n\nDeserunt consequat incididunt tempor elit sunt. Magna nulla ullamco do ut irure mollit voluptate elit dolor laboris nulla ex enim aliquip. Laboris fugiat non tempor tempor dolor aliquip eu duis enim ea culpa elit in.\n\nIncididunt do aliqua excepteur fugiat nisi cillum dolor ut esse. Reprehenderit laborum proident est voluptate irure commodo amet fugiat esse. Sint culpa excepteur sunt tempor pariatur in officia laborum in sit. Laboris laboris consectetur nostrud mollit nisi ad id culpa dolor occaecat nisi. Eu ut ea aute elit minim et proident id in aliqua tempor elit.\n`
  },
  {
    title: 'Second Blog Post',
    slug: 'second-blog-post',
    body: `This is the most recent blog post. It's being sorted by creation date, but you could add a 'Date' field, or write a custom sorting function. It's up to you!\n\nIn consectetur incididunt irure duis culpa. Qui sint labore voluptate elit adipisicing velit non nulla et. Est excepteur anim officia sunt laboris exercitation. Dolore voluptate commodo nostrud occaecat.\n\nIn voluptate ipsum deserunt voluptate. Elit mollit ut dolor dolore laboris amet voluptate et amet do proident. Lorem minim non sunt cupidatat do adipisicing velit pariatur occaecat est irure incididunt commodo officia. Lorem est excepteur est consequat aliquip.\n\nUt fugiat sunt esse minim cupidatat eiusmod nulla. Mollit laboris dolor et officia qui proident cupidatat veniam elit magna nulla laboris deserunt amet. Occaecat fugiat consequat culpa amet adipisicing id sunt ullamco cupidatat. Aliquip quis culpa occaecat veniam veniam eiusmod. Nulla adipisicing veniam nisi aute aliqua aute ex ex quis ex reprehenderit. Nostrud minim ipsum magna commodo laborum fugiat consectetur qui.\n`
  }
]
